// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shared_mem_init
SEXP shared_mem_init(std::string name, double length);
RcppExport SEXP _shmemr_shared_mem_init(SEXP nameSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< double >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(shared_mem_init(name, length));
    return rcpp_result_gen;
END_RCPP
}
// file_mem_init
SEXP file_mem_init(std::string name, double length);
RcppExport SEXP _shmemr_file_mem_init(SEXP nameSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< double >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(file_mem_init(name, length));
    return rcpp_result_gen;
END_RCPP
}
// mem_attach
void mem_attach(SEXP mem);
RcppExport SEXP _shmemr_mem_attach(SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    mem_attach(mem);
    return R_NilValue;
END_RCPP
}
// mem_detach
void mem_detach(SEXP mem);
RcppExport SEXP _shmemr_mem_detach(SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    mem_detach(mem);
    return R_NilValue;
END_RCPP
}
// is_mem_attached
bool is_mem_attached(SEXP mem);
RcppExport SEXP _shmemr_is_mem_attached(SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    rcpp_result_gen = Rcpp::wrap(is_mem_attached(mem));
    return rcpp_result_gen;
END_RCPP
}
// get_mem_address
SEXP get_mem_address(SEXP mem);
RcppExport SEXP _shmemr_get_mem_address(SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mem_address(mem));
    return rcpp_result_gen;
END_RCPP
}
// get_mem_length
double get_mem_length(SEXP mem);
RcppExport SEXP _shmemr_get_mem_length(SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mem_length(mem));
    return rcpp_result_gen;
END_RCPP
}
// get_mem_id
std::string get_mem_id(SEXP mem);
RcppExport SEXP _shmemr_get_mem_id(SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mem_id(mem));
    return rcpp_result_gen;
END_RCPP
}
// mem_remove
void mem_remove(SEXP mem);
RcppExport SEXP _shmemr_mem_remove(SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    mem_remove(mem);
    return R_NilValue;
END_RCPP
}
// mem_resize
void mem_resize(SEXP mem, double new_length);
RcppExport SEXP _shmemr_mem_resize(SEXP memSEXP, SEXP new_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mem(memSEXP);
    Rcpp::traits::input_parameter< double >::type new_length(new_lengthSEXP);
    mem_resize(mem, new_length);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shmemr_shared_mem_init", (DL_FUNC) &_shmemr_shared_mem_init, 2},
    {"_shmemr_file_mem_init", (DL_FUNC) &_shmemr_file_mem_init, 2},
    {"_shmemr_mem_attach", (DL_FUNC) &_shmemr_mem_attach, 1},
    {"_shmemr_mem_detach", (DL_FUNC) &_shmemr_mem_detach, 1},
    {"_shmemr_is_mem_attached", (DL_FUNC) &_shmemr_is_mem_attached, 1},
    {"_shmemr_get_mem_address", (DL_FUNC) &_shmemr_get_mem_address, 1},
    {"_shmemr_get_mem_length", (DL_FUNC) &_shmemr_get_mem_length, 1},
    {"_shmemr_get_mem_id", (DL_FUNC) &_shmemr_get_mem_id, 1},
    {"_shmemr_mem_remove", (DL_FUNC) &_shmemr_mem_remove, 1},
    {"_shmemr_mem_resize", (DL_FUNC) &_shmemr_mem_resize, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_shmemr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
