# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mem_init <- function(name, length, type) {
    .Call(`_shmemr_mem_init`, name, length, type)
}

mem_attach <- function(x) {
    invisible(.Call(`_shmemr_mem_attach`, x))
}

mem_detach <- function(x) {
    invisible(.Call(`_shmemr_mem_detach`, x))
}

is_mem_attached <- function(x) {
    .Call(`_shmemr_is_mem_attached`, x)
}

get_mem_address <- function(x) {
    .Call(`_shmemr_get_mem_address`, x)
}

get_mem_length <- function(x) {
    .Call(`_shmemr_get_mem_length`, x)
}

get_mem_id <- function(x) {
    .Call(`_shmemr_get_mem_id`, x)
}

mem_remove <- function(x) {
    invisible(.Call(`_shmemr_mem_remove`, x))
}

mem_resize <- function(x, new_length) {
    invisible(.Call(`_shmemr_mem_resize`, x, new_length))
}

mem_addr_str <- function(x) {
    .Call(`_shmemr_mem_addr_str`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_shmemr_RcppExport_registerCCallable', PACKAGE = 'shmemr')
})
